version: '3.8'

services:
  zombies_db:
    container_name: zombies_db
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    env_file:
      - ./api/.env.docker
    # environment:
    #   POSTGRES_DB: ${DATABASE_NAME}
    #   POSTGRES_USER: ${DATABASE_USERNAME}
    #   POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - zombies-network
  zombies_dev:
    container_name: zombies_dev
    image: zombies-dev:1.0.0
    build:
      context: .
      target: install
      dockerfile: ./Dockerfile
    working_dir: /home/node/api
    env_file:
      - ./api/.env.docker
    command: npm run start:dev #:debug
    depends_on:
      - zombies_db
    ports:
      - 3000:3000
      # - 9229:9229
    networks:
      - zombies-network
    volumes:
      - ./api:/home/node/api
      - ./app:/home/node/app
      - ./channels.data.json:/home/node/channels.data.json
      - ./websites.data.json:/home/node/websites.data.json
    restart: unless-stopped

networks:
  zombies-network:
  