version: "3"

services:
  db:
    # image: mongo # container image to be used
    # restart: always 
    # ports: # expose ports in “host:container” format
    #   - 27017:27017
    # environment: #env variables to pass into the container
    #    MONGODB_DATABASE: zombies
    image:  postgres
    restart: always 
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data